require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Administrador::FamiliesController do

  # This should return the minimal set of attributes required to create a valid
  # Administrador::Family. As you add validations to Administrador::Family, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Administrador::FamiliesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all administrador_families as @administrador_families" do
      family = Administrador::Family.create! valid_attributes
      get :index, {}, valid_session
      assigns(:administrador_families).should eq([family])
    end
  end

  describe "GET show" do
    it "assigns the requested administrador_family as @administrador_family" do
      family = Administrador::Family.create! valid_attributes
      get :show, {:id => family.to_param}, valid_session
      assigns(:administrador_family).should eq(family)
    end
  end

  describe "GET new" do
    it "assigns a new administrador_family as @administrador_family" do
      get :new, {}, valid_session
      assigns(:administrador_family).should be_a_new(Administrador::Family)
    end
  end

  describe "GET edit" do
    it "assigns the requested administrador_family as @administrador_family" do
      family = Administrador::Family.create! valid_attributes
      get :edit, {:id => family.to_param}, valid_session
      assigns(:administrador_family).should eq(family)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Administrador::Family" do
        expect {
          post :create, {:administrador_family => valid_attributes}, valid_session
        }.to change(Administrador::Family, :count).by(1)
      end

      it "assigns a newly created administrador_family as @administrador_family" do
        post :create, {:administrador_family => valid_attributes}, valid_session
        assigns(:administrador_family).should be_a(Administrador::Family)
        assigns(:administrador_family).should be_persisted
      end

      it "redirects to the created administrador_family" do
        post :create, {:administrador_family => valid_attributes}, valid_session
        response.should redirect_to(Administrador::Family.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved administrador_family as @administrador_family" do
        # Trigger the behavior that occurs when invalid params are submitted
        Administrador::Family.any_instance.stub(:save).and_return(false)
        post :create, {:administrador_family => {}}, valid_session
        assigns(:administrador_family).should be_a_new(Administrador::Family)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Administrador::Family.any_instance.stub(:save).and_return(false)
        post :create, {:administrador_family => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested administrador_family" do
        family = Administrador::Family.create! valid_attributes
        # Assuming there are no other administrador_families in the database, this
        # specifies that the Administrador::Family created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Administrador::Family.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => family.to_param, :administrador_family => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested administrador_family as @administrador_family" do
        family = Administrador::Family.create! valid_attributes
        put :update, {:id => family.to_param, :administrador_family => valid_attributes}, valid_session
        assigns(:administrador_family).should eq(family)
      end

      it "redirects to the administrador_family" do
        family = Administrador::Family.create! valid_attributes
        put :update, {:id => family.to_param, :administrador_family => valid_attributes}, valid_session
        response.should redirect_to(family)
      end
    end

    describe "with invalid params" do
      it "assigns the administrador_family as @administrador_family" do
        family = Administrador::Family.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Administrador::Family.any_instance.stub(:save).and_return(false)
        put :update, {:id => family.to_param, :administrador_family => {}}, valid_session
        assigns(:administrador_family).should eq(family)
      end

      it "re-renders the 'edit' template" do
        family = Administrador::Family.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Administrador::Family.any_instance.stub(:save).and_return(false)
        put :update, {:id => family.to_param, :administrador_family => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested administrador_family" do
      family = Administrador::Family.create! valid_attributes
      expect {
        delete :destroy, {:id => family.to_param}, valid_session
      }.to change(Administrador::Family, :count).by(-1)
    end

    it "redirects to the administrador_families list" do
      family = Administrador::Family.create! valid_attributes
      delete :destroy, {:id => family.to_param}, valid_session
      response.should redirect_to(administrador_families_url)
    end
  end

end
